"use client";

import { useMemo, useState } from "react";
import { FileText, Plus, Search, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { Account, PublicationTemplate, PublicationVariant, TemplateMode } from "../models/dashboard";
import { PanelHeader } from "../components/PanelHeader";

export function PublicationTab({ accounts, cities, templates, createTemplate, deleteTemplate, activateTemplate, deactivateTemplate, updateTemplateName, updateTemplateAccounts, updateTemplateCities, updateTemplateMode, updateTemplateAutoCount, updateTemplateVariants, toggleTemplateMigration }: { accounts: Account[]; cities: string[]; templates: PublicationTemplate[]; createTemplate: () => void; deleteTemplate: (id: number) => void; activateTemplate: (id: number) => void; deactivateTemplate: (id: number) => void; updateTemplateName: (id: number, name: string) => void; updateTemplateAccounts: (id: number, value: string[]) => void; updateTemplateCities: (id: number, value: string[]) => void; updateTemplateMode: (id: number, mode: TemplateMode) => void; updateTemplateAutoCount: (id: number, value: number) => void; updateTemplateVariants: (id: number, variants: PublicationVariant[]) => void; toggleTemplateMigration: (id: number) => void }) {
  return <Card className="light-panel text-ink-900"><PanelHeader icon={FileText} title="Шаблоны" action={<Button size="sm" onClick={createTemplate}><Plus className="h-4 w-4" /> Создать</Button>} /><div className="grid gap-4 p-5 pt-0 md:grid-cols-2">{templates.map(template => <TemplateCard key={template.id} template={template} accountNames={accounts.map(account => account.name)} cities={cities} deleteTemplate={deleteTemplate} activateTemplate={activateTemplate} deactivateTemplate={deactivateTemplate} updateTemplateName={updateTemplateName} updateTemplateAccounts={updateTemplateAccounts} updateTemplateCities={updateTemplateCities} updateTemplateMode={updateTemplateMode} updateTemplateAutoCount={updateTemplateAutoCount} updateTemplateVariants={updateTemplateVariants} toggleTemplateMigration={toggleTemplateMigration} />)}{templates.length === 0 && <div className="col-span-full rounded-3xl border border-dashed border-primary-300 bg-primary-50 p-10 text-center text-ink-500">Шаблонов пока нет</div>}</div></Card>;
}

function TemplateCard({ template, accountNames, cities, deleteTemplate, activateTemplate, deactivateTemplate, updateTemplateName, updateTemplateAccounts, updateTemplateCities, updateTemplateMode, updateTemplateAutoCount, updateTemplateVariants, toggleTemplateMigration }: { template: PublicationTemplate; accountNames: string[]; cities: string[]; deleteTemplate: (id: number) => void; activateTemplate: (id: number) => void; deactivateTemplate: (id: number) => void; updateTemplateName: (id: number, name: string) => void; updateTemplateAccounts: (id: number, value: string[]) => void; updateTemplateCities: (id: number, value: string[]) => void; updateTemplateMode: (id: number, mode: TemplateMode) => void; updateTemplateAutoCount: (id: number, value: number) => void; updateTemplateVariants: (id: number, variants: PublicationVariant[]) => void; toggleTemplateMigration: (id: number) => void }) {
  const toggleValue = (value: string, values: string[], onChange: (value: string[]) => void) => onChange(values.includes(value) ? values.filter(item => item !== value) : [...values, value]);
  const addVariant = () => updateTemplateVariants(template.id, [...template.variants, { id: Date.now(), name: `Объявление ${template.variants.length + 1}`, count: 10 }]);
  const updateVariantCount = (id: number, count: number) => updateTemplateVariants(template.id, template.variants.map(item => item.id === id ? { ...item, count } : item));
  const deleteVariant = (id: number) => updateTemplateVariants(template.id, template.variants.filter(item => item.id !== id));

  return <div className={`rounded-3xl border bg-white/78 p-5 shadow-[0_16px_42px_rgba(20,85,255,.08)] ${template.active ? "border-success/40" : "border-primary-900/10"}`}>
    <div className="mb-4 flex items-center justify-between gap-3"><Input maxLength={64} value={template.name} onChange={event => updateTemplateName(template.id, event.target.value)} className="h-9 border-0 bg-transparent p-0 text-base font-black text-ink-900" /><div className="flex items-center gap-2">{template.active && <Badge variant="success">Активен</Badge>}<Button size="icon" variant="ghost" className="h-8 w-8 text-danger hover:bg-danger/10" onClick={() => deleteTemplate(template.id)}><Trash2 className="h-5 w-5" /></Button></div></div>
    <SearchableSelector label="Аккаунты" placeholder="Поиск аккаунта…" values={accountNames} selected={template.accounts} onToggle={value => toggleValue(value, template.accounts, next => updateTemplateAccounts(template.id, next))} />
    <SearchableSelector label="Города (гео)" placeholder="Поиск города…" values={cities} selected={template.cities} onToggle={value => toggleValue(value, template.cities, next => updateTemplateCities(template.id, next))} />
    <div className="mt-4 rounded-2xl border border-primary-900/10 bg-primary-50 p-4"><div className="mb-3 flex items-center justify-between gap-3"><span className="font-bold">Варианты объявлений</span><div className="rounded-full bg-white p-1">{(["auto", "manual"] as const).map(mode => <button key={mode} onClick={() => updateTemplateMode(template.id, mode)} className={`rounded-full px-3 py-1 text-xs font-black ${template.mode === mode ? "bg-primary-600 text-white" : "text-primary-700/50"}`}>{mode === "auto" ? "АВТО" : "ВРУЧНУЮ"}</button>)}</div></div>
      <div className="space-y-2">{template.variants.map(variant => <div key={variant.id} className="flex items-center gap-2 rounded-xl border border-primary-200 bg-white px-3 py-2"><span className="flex-1 font-semibold text-ink-900">{variant.name}</span>{template.mode === "manual" && <Input type="number" min={1} max={500} value={variant.count} onChange={event => updateVariantCount(variant.id, Number(event.target.value) || 1)} className="h-8 w-20 text-center font-black text-primary-700" />}<Button variant="ghost" size="icon" className="h-8 w-8 text-danger hover:bg-danger/10" onClick={() => deleteVariant(variant.id)}><Trash2 className="h-4 w-4" /></Button></div>)}</div>
      <Button variant="ghost" size="sm" className="mt-2 text-primary-700" onClick={addVariant}><Plus className="h-4 w-4" /> Создать объявление</Button>
      {template.mode === "auto" && <div className="mt-3 flex items-center justify-between border-t border-primary-900/10 pt-3 text-sm"><span className="text-ink-500">Кол-во публикаций на аккаунт</span><Input type="number" min={1} max={500} value={template.autoCount} onChange={event => updateTemplateAutoCount(template.id, Number(event.target.value) || 1)} className="h-9 w-20 text-center font-black text-primary-700" /></div>}
    </div>
    <button type="button" onClick={() => toggleTemplateMigration(template.id)} className={`mt-4 flex w-full items-center justify-between rounded-2xl border px-4 py-3 text-left text-sm font-bold ${template.migrationEnabled ? "border-primary-300 bg-primary-50 text-primary-700" : "border-primary-900/10 bg-white text-ink-600"}`}><span>Миграция лучших объявлений между аккаунтами</span><span className={`h-5 w-9 rounded-full p-0.5 ${template.migrationEnabled ? "bg-primary-600" : "bg-ink-200"}`}><span className={`block h-4 w-4 rounded-full bg-white transition ${template.migrationEnabled ? "translate-x-4" : ""}`} /></span></button>
    <Button className="mt-4 w-full rounded-2xl" variant={template.active ? "destructive" : "default"} onClick={() => template.active ? deactivateTemplate(template.id) : activateTemplate(template.id)}>{template.active ? "Деактивировать" : "Активировать"}</Button>
    {(template.accounts.length === 0 || template.cities.length === 0) && !template.active && <div className="mt-2 text-center text-xs text-warning">Для активации выберите аккаунт и город</div>}
  </div>;
}

function SearchableSelector({ label, placeholder, values, selected, onToggle }: { label: string; placeholder: string; values: string[]; selected: string[]; onToggle: (value: string) => void }) {
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => values.filter(value => value.toLowerCase().includes(query.toLowerCase())), [values, query]);
  return <div className="mb-3"><div className="mb-2 text-[10px] font-black uppercase tracking-wider text-ink-400">{label}</div><div className="relative mb-2"><Search className="absolute left-3 top-2.5 h-4 w-4 text-ink-400" /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder={placeholder} className="h-9 rounded-xl border-primary-900/10 bg-white pl-9 text-ink-900" /></div><div className="flex max-h-40 flex-wrap gap-2 overflow-y-auto rounded-2xl border border-primary-900/10 bg-primary-50/60 p-2">{filtered.map(value => <button key={value} onClick={() => onToggle(value)} className={`rounded-full border px-3 py-1.5 text-xs font-bold ${selected.includes(value) ? "border-primary-300 bg-primary-600 text-white" : "border-primary-900/10 bg-white text-primary-700"}`}>{value}</button>)}</div></div>;
}
