"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { AlertTriangle, BarChart3, CheckSquare2, ChevronRight, CirclePause, FileText, Plus, RefreshCw, Search, Send, Settings2, Trash2, UserRound, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";

type Tab = "manager" | "publication" | "updates";
const accounts = ["Applexis", "MotoDrive", "HomeCraft", "TechMarket", "AutoPartsPro"];
const cities = ["Москва", "Санкт‑Петербург", "Казань", "Краснодар", "Екатеринбург"];
const tasks = [
  { id: 1, title: "Публикация AirPods Pro", account: "Applexis", progress: 72, status: "running" },
  { id: 2, title: "Загрузка запчастей Toyota", account: "MotoDrive, AutoPartsPro", progress: 27, status: "queue" },
  { id: 3, title: "Обновление описаний", account: "HomeCraft", progress: 0, status: "error", error: "Ошибка авторизации: access_token истёк. Будет выполнен auto-refresh через refresh_token." }
];
const initialListings = Array.from({ length: 8 }).map((_, i) => ({ id: i + 1, avitoId: 8320100 + i, title: ["iPhone 15 Pro 256GB", "BMW X5 G05", "Диван угловой Moon", "AirPods Pro 2", "Toyota Camry фара", "MacBook Air M2", "Кресло офисное", "Шины Michelin"][i], price: [99000, 6200000, 45000, 17900, 12500, 87000, 12900, 36000][i], mode: i % 3 === 0 ? "auto" : "manual", selected: i < 3, updated: i % 2 ? "48 мин назад" : "2 ч назад" }));

export default function DashboardPage() {
  const [tab, setTab] = useState<Tab>("manager");
  return <main className="min-h-screen bg-blue-radial text-white"><div className="dot-grid pointer-events-none fixed inset-0 opacity-30" /><div className="container relative z-10 py-6"><Header /><HeroStats /><TabSwitcher tab={tab} setTab={setTab} /><section className="mx-auto mt-5 max-w-5xl">{tab === "manager" && <ManagerTab />}{tab === "publication" && <PublicationTab />}{tab === "updates" && <UpdatesTab />}</section></div></main>;
}

function Header() { return <header className="mb-5 flex items-center justify-between"><Link href="/" className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-primary-600 shadow-glow font-black">A</div><div><div className="font-black tracking-tight">AviEngine</div><div className="text-xs text-white/45">Enterprise Console</div></div></Link><div className="flex items-center gap-3"><Button variant="secondary" size="sm"><UserRound className="h-4 w-4" /> Аккаунты</Button><Button size="sm">Привязать Авито</Button></div></header>; }
function HeroStats() { return <Card className="overflow-hidden rounded-[1.7rem]"><div className="relative bg-gradient-to-br from-primary-700 via-primary-600 to-cyan/70 p-6"><div className="absolute inset-0 dot-grid opacity-25" /><div className="relative flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><Badge className="bg-white/15 text-white">OAuth подключён · Autoload ready</Badge><h1 className="mt-4 text-3xl font-black tracking-tight md:text-5xl">Панель управления публикациями</h1><p className="mt-3 max-w-2xl text-white/65">Сохранён UX прототипа: hero, аккаунты, менеджер задач, публикация шаблонов. Добавлена вкладка «Обновление».</p></div><div className="grid grid-cols-3 gap-3"><MiniStat v="12" l="слотов" /><MiniStat v="348" l="объявлений" /><MiniStat v="97%" l="успешно" /></div></div></div></Card>; }
function MiniStat({ v, l }: { v: string; l: string }) { return <div className="rounded-2xl border border-white/15 bg-white/12 p-4 text-center backdrop-blur"><div className="text-2xl font-black">{v}</div><div className="text-xs text-white/60">{l}</div></div>; }
function TabSwitcher({ tab, setTab }: { tab: Tab; setTab: (t: Tab) => void }) { const tabs = [{ id: "manager", label: "Менеджер задач", icon: CheckSquare2 }, { id: "publication", label: "Публикация", icon: Send }, { id: "updates", label: "Обновление", icon: RefreshCw }] as const; return <div className="mt-5 flex justify-center gap-2">{tabs.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`flex items-center gap-2 rounded-full border px-5 py-2.5 text-sm font-bold transition ${tab === id ? "border-white/35 bg-white/20 text-white shadow-glass" : "border-white/10 bg-white/[.06] text-white/48 hover:text-white"}`}><Icon className="h-4 w-4" />{label}{tab === id && <span className="h-1.5 w-1.5 rounded-full bg-cyan" />}</button>)}</div>; }

function ManagerTab() { const errors = tasks.filter(t => t.status === "error"); return <div className="space-y-5"><Card className="light-panel overflow-hidden text-ink-900"><PanelHeader icon={CheckSquare2} title="Менеджер задач" action={<Button size="sm"><Zap className="h-4 w-4" /> Запустить агента</Button>} /><div className="grid grid-cols-3 border-y border-primary-900/10 text-sm"><Kpi l="Выполнено" v="54%" /><Kpi l="Активных задач" v="3" /><Kpi l="Ошибки" v={String(errors.length)} danger /></div><div className="p-4"><div className="mb-3 flex items-center gap-2 text-xs font-black uppercase tracking-wider text-primary-700"><span className="h-2 w-2 rounded-full bg-primary-600" /> В процессе</div>{tasks.filter(t => t.status !== "error").map(t => <TaskRow key={t.id} t={t} />)}</div>{errors.length > 0 && <div className="border-t border-danger/15 bg-danger/[.045] p-4"><div className="mb-3 flex items-center gap-2 text-xs font-black uppercase tracking-wider text-danger"><AlertTriangle className="h-4 w-4" /> Ошибки <Badge variant="danger">{errors.length}</Badge></div>{errors.map(t => <div key={t.id} className="rounded-2xl border border-danger/15 bg-white/70 p-4"><div className="flex items-start justify-between gap-4"><div><b>{t.title}</b><p className="mt-1 text-sm text-danger">{t.error}</p><p className="mt-2 text-xs text-ink-500">Система покажет причину и техническое действие. Автоматического AI‑исправления в интерфейсе нет.</p></div><Button variant="destructive" size="icon"><Trash2 className="h-4 w-4" /></Button></div></div>)}</div>}</Card></div>; }
function PanelHeader({ icon: Icon, title, action }: any) { return <div className="flex items-center justify-between gap-4 p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-primary-600/10 text-primary-700"><Icon className="h-5 w-5" /></div><h2 className="text-lg font-black">{title}</h2></div>{action}</div>; }
function Kpi({ l, v, danger }: { l: string; v: string; danger?: boolean }) { return <div className="p-4"><div className="text-xs text-ink-500">{l}</div><div className={`mt-1 text-xl font-black ${danger ? "text-danger" : "text-primary-700"}`}>{v}</div></div>; }
function TaskRow({ t }: any) { return <div className="mb-3 rounded-2xl border border-primary-900/10 bg-white/70 p-4"><div className="mb-3 flex items-center justify-between"><div><b>{t.title}</b><div className="mt-1 text-xs text-ink-500">{t.account}</div></div><Badge variant={t.status === "queue" ? "warning" : "blue"}>{t.status === "queue" ? "Очередь" : "Работает"}</Badge></div><div className="h-2 overflow-hidden rounded-full bg-primary-100"><div className="h-full rounded-full bg-gradient-to-r from-primary-600 to-cyan" style={{ width: `${t.progress}%` }} /></div></div>; }

function PublicationTab() { return <div className="space-y-5"><Card className="light-panel text-ink-900"><PanelHeader icon={FileText} title="Шаблоны публикаций" action={<Button size="sm"><Plus className="h-4 w-4" /> Создать</Button>} /><div className="grid gap-4 p-5 pt-0 md:grid-cols-2">{["Авто — BMW X5", "Электроника — iPhone 15 Pro", "Мебель — Диван угловой"].map((name, i) => <TemplateCard key={name} name={name} active={i === 0} />)}</div></Card></div>; }
function TemplateCard({ name, active }: { name: string; active?: boolean }) { return <div className="rounded-3xl border border-primary-900/10 bg-white/72 p-5"><div className="mb-4 flex items-center justify-between"><b>{name}</b>{active ? <Badge variant="success">Активен</Badge> : <Button size="sm">Активировать</Button>}</div><Field label="Аккаунты" value={accounts.slice(0, 2).join(", ")} /><Field label="Города" value={cities.slice(0, 3).join(", ")} /><div className="mt-4 rounded-2xl bg-primary-50 p-4"><div className="mb-3 flex items-center justify-between"><span className="font-bold">Варианты объявлений</span><Badge variant="blue">АВТО</Badge></div><button className="flex w-full items-center justify-between rounded-xl border border-primary-200 bg-white px-4 py-3 text-left text-sm font-semibold">Базовый <ChevronRight className="h-4 w-4" /></button><Button variant="ghost" size="sm" className="mt-2 text-primary-700"><Plus className="h-4 w-4" /> Создать объявление</Button></div></div>; }
function Field({ label, value }: { label: string; value: string }) { return <div className="mb-3"><div className="mb-1 text-[10px] font-black uppercase tracking-wider text-ink-400">{label}</div><div className="rounded-xl border border-primary-900/10 bg-primary-50 px-3 py-2 text-sm text-ink-700">{value}</div></div>; }

function UpdatesTab() { const [listings, setListings] = useState(initialListings); const selected = useMemo(() => listings.filter(l => l.selected).length, [listings]); const toggleAll = () => setListings(p => p.map(l => ({ ...l, selected: selected !== listings.length }))); return <Card className="light-panel text-ink-900"><PanelHeader icon={RefreshCw} title="Обновление" action={<div className="flex gap-2"><Button variant="secondary" size="sm" className="bg-primary-50 text-primary-700"><Settings2 className="h-4 w-4" /> Режимы</Button><Button size="sm">Обновить сейчас</Button></div>} /><div className="border-y border-primary-900/10 p-5"><div className="grid gap-4 md:grid-cols-[1fr_220px_220px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-ink-400" /><Input className="border-primary-900/10 bg-white pl-9 text-ink-900 placeholder:text-ink-400" placeholder="Поиск по объявлениям" /></div><ModeCard title="Авто режим" text="Система выбирает время" active /><ModeCard title="Ручной режим" text="Кнопка обновления" /></div><button onClick={toggleAll} className="mt-4 text-sm font-bold text-primary-700">{selected === listings.length ? "Снять выбор" : "Выбрать все"} · выбрано {selected}</button></div><div className="grid gap-4 p-5 md:grid-cols-2 lg:grid-cols-4">{listings.map(item => <ListingCard key={item.id} item={item} onToggle={() => setListings(p => p.map(l => l.id === item.id ? { ...l, selected: !l.selected } : l))} />)}</div></Card>; }
function ModeCard({ title, text, active }: { title: string; text: string; active?: boolean }) { return <div className={`rounded-2xl border p-4 ${active ? "border-primary-300 bg-primary-50" : "border-primary-900/10 bg-white"}`}><div className="font-black">{title}</div><div className="mt-1 text-xs text-ink-500">{text}</div></div>; }
function ListingCard({ item, onToggle }: any) { return <div className={`rounded-3xl border p-3 transition ${item.selected ? "border-primary-300 bg-primary-50" : "border-primary-900/10 bg-white"}`}><div className="mb-3 flex items-center justify-between"><Checkbox checked={item.selected} onCheckedChange={onToggle} /><Badge variant={item.mode === "auto" ? "blue" : "default"}>{item.mode === "auto" ? "auto" : "manual"}</Badge></div><div className="mb-3 h-28 rounded-2xl bg-gradient-to-br from-primary-100 to-cyan/20" /><b className="line-clamp-2 text-sm">{item.title}</b><div className="mt-2 text-lg font-black">{item.price.toLocaleString("ru-RU")} ₽</div><div className="mt-2 text-xs text-ink-500">Avito ID {item.avitoId} · {item.updated}</div></div>; }
